### ISSUE TITLE
Deluge v1.3 support?

### ISSUE THREAD

**Issue by etnoy** [rehanone/puppet-deluge#12]
Thanks for this module.

I would love to use deluge 2.0, but it's still so new that many of the systems interfacing with deluge have trouble, especially as 2.0 is still missing some functionality, not to mention the lack of a Windows client :)

Deluge 2.0 is clearly superior, but until it matures I will need to stay on 1.3. Perhaps there could be a parameter to choose the legacy version for now?

**Comment by rehanone** [comment]
Thanks for using this repo and suggesting to retain the support for v1.3. I did not realize this repo was used as I never published it on the forge.

I think it is very easy to revert back to the older version by setting the following attribute:

`deluge::repo_sources: 'ppa:deluge-team/ppa'`

Please try and let me know if that works for you.
